GLOBAL_PROPERTIES = [
    "item",
    "store",
    "display_name",
    "pickup_location",
    "items_available",
    "distance",
    "favorite",
    "in_sales_window",
    "new_item",
    "item_type",
]
STORE_PROPERTIES = [
    "store_id",
    "store_name",
    "description",
    "tax_identifier",
    "website",
    "store_location",
    "logo_picture",
    "store_time_zone",
    "hidden",
    "favorite_count",
    "items",
    "milestones",
    "we_care",
    "distance",
    "cover_picture",
    "is_manufacturer",
]
ITEM_PROPERTIES = [
    "item_id",
    "sales_taxes",
    "tax_amount",
    "price_excluding_taxes",
    "price_including_taxes",
    "value_excluding_taxes",
    "value_including_taxes",
    "taxation_policy",
    "show_sales_taxes",
    "cover_picture",
    "logo_picture",
    "name",
    "description",
    "food_handling_instructions",
    "can_user_supply_packaging",
    "packaging_option",
    "collection_info",
    "diet_categories",
    "item_category",
    "buffet",
    "badges",
    "positive_rating_reasons",
    "average_overall_rating",
    "allergens_info",
    "favorite_count",
]

tgtg_client_fake_tokens = {
    "access_token": "access_token",
    "refresh_token": "refresh_token",
    "user_id": "user_id",
    "cookie": "cookie",
}
